version: "3.8"
services:
  db:
    image: postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: cordillera 
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 11.100.0.100

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db

networks:
  default:
    attachable: true
    ipam:
      config:
        - subnet: 11.100.0.0/16
